### ISSUE TITLE
Links to i6 doc or sample command line fan commands in readme

### ISSUE THREAD

**Issue by gt3mike** [jfroy/aiobafi6#3]
Would it be possible to update the readme with a link to the i6 docs (I searched but didn't find them) and/or command line examples to do things like turn fans off and on?

**Comment by jfroy** [comment]
I can improve the README, sure. But the command line really is meant for testing and debugging the library, not for production use.

**Comment by gt3mike** [comment]
Where can I find BAF’s API? I can probably figure out what I need from there.

**Comment by jfroy** [comment]
> Where can I find BAF’s API? I can probably figure out what I need from there. 

It's not documented. I reverse engineered it with help from a few other folks (see README) using my own fan, wireshark, and BAF's iOS app.
